---
version: '3'
services:
  graphite:
    image: matthbak/graphite:1.0.2
    ports:
      - "80:80"
      - "443:443"
      - "2003:2003"
      - "2004:2004"
      - "3000:3000"
    volumes: 
      - /srv/docker/graphite:/opt/graphite/storage
      - /srv/docker/grafana:/var/lib/grafana
      - /srv/docker/grafana.ini:/etc/grafana/grafana.ini
      - /srv/docker/grafana/logs:/var/log/grafana
